version: '3.7'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./cakeReactApi/:/app/cakeReactApi:cached
    container_name: php
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - 8080:80
    volumes:
      - ./cakeReactApi:/app/cakeReactApi:cached
      - ./docker/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
  db:
    build:
      context: ./docker/db
    container_name: db
    volumes:
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
  node:
      build:
          context: ./docker/node
      container_name: node
      tty: true
      volumes:
        - ./cakeReactFront:/app/cakeReactFront:cached
      ports:
        - "3000:3000"
     